services:
  # Backend (Node.js)
  backend:
    build: ./backend
    restart: always
    ports:
      - "3001:5000"  # Expose backend API on port 3001
    depends_on:
      - postgres
    volumes:
      - ./backend:/app  # Mount the backend directory into the container
      - /app/node_modules  # Prevents overwriting node_modules
    command: npm run dev  # Ensure hot-reloading for development (with nodemon)
    networks:
      - app-network

  # Frontend (React)
  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3000:3000"  # Expose frontend React app on port 3000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app  # Mount the frontend directory
      - /app/node_modules  # Prevents overwriting node_modules
    command: npm run dev  # Ensure React development server with hot-reloading
    networks:
      - app-network

  # Database (PostgreSQL)
  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example
    networks:
      - app-network

# Define named volumes for persistent data
volumes:
  postgres-data:

# Define networks for internal communication
networks:
  app-network:
    driver: bridge